source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '8.0'
install! 'cocoapods', :deterministic_uuids => false

target 'startup' do
    # 基础层
    pod 'Framework/Foundation', :path => '../'
    # 视图层
    pod 'Framework/UIKit', :path => '../'
  
    # 工具
    pod 'Framework/Core/Modular', :path => '../'
    pod 'Framework/Core/NetworkLit', :path => '../'
    pod 'Framework/Core/Network/Reachability', :path => '../'
    pod 'Framework/Core/Cache', :path => '../'

    pod 'Framework/Core/HttpMock', :path => '../'
    pod 'Framework/Core/Chronograph', :path => '../'
    pod 'Framework/Core/CountDown', :path => '../'
    pod 'Framework/Core/Delegate', :path => '../'
    pod 'Framework/Core/HtmlParser', :path => '../'
    
  
    # 模块
    pod 'Framework/Module/App', :path => '../'
    pod 'Framework/Module/Assets', :path => '../'
    pod 'Framework/Module/Growth', :path => '../'
    pod 'Framework/Module/Location', :path => '../'
    pod 'Framework/Module/APNS', :path => '../'
    pod 'Framework/Module/SNS', :path => '../'
#    pod '_Modules/Services/Pay', :path => '../' # Need pod 'UnionPay', :path => '../_Vendors/UnionPay'
    pod 'UnionPay', :path => '../Framework/Vendor/UnionPay'
    pod 'Framework/Module/QRCode', :path => '../'
    pod 'Framework/Module/Browser', :path => '../'
    pod 'Framework/Module/Map', :path => '../'

    pod 'Framework/Module/Image', :path => '../'
    pod 'Framework/Module/Share', :path => '../'

    ######################################
    # UI 组件
    ######################################
    
    pod 'Framework/Component/AnimatedImage', :path => '../'
    pod 'Framework/Component/ActionSheetView', :path => '../'
    pod 'Framework/Component/AlertView', :path => '../'
    pod 'Framework/Component/BadgeView', :path => '../'
    pod 'Framework/Component/BlankHolderView', :path => '../'
    pod 'Framework/Component/CycleScrollView', :path => '../'
    pod 'Framework/Component/DatePickerView', :path => '../'
    pod 'Framework/Component/DropDownMenu', :path => '../'
    pod 'Framework/Component/FiniteScrollView', :path => '../'
    pod 'Framework/Component/FlatActionSheetView', :path => '../'
#    pod 'Framework/Component/ImageBrowserView', :path => '../'
#    pod 'Framework/Component/ImagePicker', :path => '../'
    pod 'Framework/Component/IndicatorView', :path => '../'
    pod 'Framework/Component/InfiniteScrollView', :path => '../'
    pod 'Framework/Component/KeyboardControl', :path => '../'
    pod 'Framework/Component/LaunchAdView', :path => '../'
    pod 'Framework/Component/LoadableImageView', :path => '../'
    
    pod 'Framework/Component/LocalImageBrowser', :path => '../'
    pod 'Framework/Component/LocalImageEditableBrowserView', :path => '../'
    pod 'Framework/Component/PopupView', :path => '../'
    pod 'Framework/Component/PopViewController', :path => '../'
    pod 'Framework/Component/ProgressHUD', :path => '../'
    pod 'Framework/Component/ProgressView', :path => '../'

#    pod 'Framework/Component/QRCodeReaderView', :path => '../'

    pod 'Framework/Component/PopViewController', :path => '../'
    pod 'Framework/Component/RateView', :path => '../'
    pod 'Framework/Component/RefreshView', :path => '../'
    pod 'Framework/Component/SegmentControl', :path => '../'
    pod 'Framework/Component/SegmentView', :path => '../'
    pod 'Framework/Component/TagsView', :path => '../'
    pod 'Framework/Component/UserGuideView', :path => '../'
    pod 'Framework/Component/WaterFallView', :path => '../'
    
    ######################################
    # 其他依赖
    ######################################
    
    pod 'ReactiveObjC'
    pod 'Masonry'
    pod 'YYModel'
    pod 'SDWebImage', '~> 4.0'
    pod 'AFNetworking', '~> 3.0'
    pod 'GTMBase64'
    
    # pod 'RealReachability' # 非网络连接状态，而是网络到达状态，比如：Wi-Fi 并 能否连接到www.baidu.com
    # pod 'TransitionKit', '~> 2.0.0' # 状态机
    # pod 'Objective-Chain'
    # pod 'JHChainableAnimations', '~> 3.0.1' # While use 'ChainableAnimations' in Swift
    # pod 'RegexKitLite' # 正则表达式
    
    ######################################
    # 其他 UI 组件
    ######################################
    
    # 抽屉
    #pod "JVFloatingDrawer"
    
    # 类似网易新闻、今日头条、虎扑看球等app做的一个顶部菜单栏，每栏中有独立的控制器，可自己定制。
    # pod 'NinaPagerView'
    # pod 'MXSegmentedPager'
    
    # pod 'SDAutoLayout'
    # pod 'SDCycleScrollView'
    
    pod 'TZImagePickerController'

end
